# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/kuro/Principles_of_Computer_Organization/lab/lab5/lab5_vivado/lab5_vivado.srcs/sources_1/ip/DATA_MEM/DATA_MEM.xci
# IP: The module: 'DATA_MEM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/kuro/Principles_of_Computer_Organization/lab/lab5/lab5_vivado/lab5_vivado.gen/sources_1/ip/DATA_MEM/DATA_MEM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DATA_MEM'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/kuro/Principles_of_Computer_Organization/lab/lab5/lab5_vivado/lab5_vivado.srcs/sources_1/ip/DATA_MEM/DATA_MEM.xci
# IP: The module: 'DATA_MEM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/kuro/Principles_of_Computer_Organization/lab/lab5/lab5_vivado/lab5_vivado.gen/sources_1/ip/DATA_MEM/DATA_MEM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DATA_MEM'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
