# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/kuro/Principles_of_Computer_Organization/lab/lab6/constraints_0415.xdc

# IP: ip/INST_MEM/INST_MEM.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==INST_MEM || ORIG_REF_NAME==INST_MEM} -quiet] -quiet
